name: Standard
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/standard.yml
      - standard/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -f standard/Dockerfile -t ankane/ml-stack:standard .

      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ankane/ml-stack:standard
