name: Torch GPU
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/torch-gpu.yml
      - torch-gpu/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -f torch-gpu/Dockerfile -t ankane/ml-stack:torch-gpu .

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ankane/ml-stack:torch-gpu
